- job:
    name: oslodb-tox-py38-tips
    parent: openstack-tox-py38
    description: |
      Run unit tests for oslo.db with main branch of important libs.
      Takes advantage of the base tox job's install-siblings feature.
    # The job only tests the latest and shouldn't be run on the stable branches
    branches: ^(?!stable)
    required-projects:
      - name: github.com/sqlalchemy/sqlalchemy
        override-checkout: main
      - name: github.com/sqlalchemy/alembic
        override-checkout: main
    vars:
      # Set work dir to oslo.db so that if it's triggered by one of the
      # other repos the tests will run in the same place
      zuul_work_dir: src/opendev.org/openstack/oslo.db

- job:
    name: oslodb-tox-py310-tips
    parent: openstack-tox-py310
    description: |
      Run unit tests for oslo.db with main branch of important libs.
      Takes advantage of the base tox job's install-siblings feature.
    # The job only tests the latest and shouldn't be run on the stable branches
    branches: ^(?!stable)
    required-projects:
      - name: github.com/sqlalchemy/sqlalchemy
        override-checkout: main
      - name: github.com/sqlalchemy/alembic
        override-checkout: main
    vars:
      # Set work dir to oslo.db so that if it's triggered by one of the
      # other repos the tests will run in the same place
      zuul_work_dir: src/opendev.org/openstack/oslo.db

- project-template:
    name: oslodb-tox-unit-tips
    check:
      jobs:
        - oslodb-tox-py38-tips
        - oslodb-tox-py310-tips
    gate:
      jobs:
        - oslodb-tox-py38-tips
        - oslodb-tox-py310-tips

- project:
    templates:
      - oslodb-tox-unit-tips
      - check-requirements
      - lib-forward-testing-python3
      - openstack-python3-jobs
      - periodic-stable-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
